<!doctype html><html lang="id"><head><meta charset="utf-8"><title>Data Saya</title><style>
@page{margin:20mm 16mm}body{font-family:DejaVu Sans,sans-serif;color:#1e293b;font-size:10px}header{border-bottom:3px solid #d4ac0d;padding-bottom:10px;margin-bottom:16px}.brand{font-size:11px;font-weight:bold;color:#003857;text-transform:uppercase}h1{font-size:20px;color:#003857;margin:5px 0}.meta{color:#64748b;font-size:8px}h2{font-size:12px;background:#003857;color:white;padding:7px 9px;margin:14px 0 0}table{border-collapse:collapse;width:100%}td{border-bottom:1px solid #cbd5e1;padding:7px 8px;vertical-align:top}td:first-child{color:#64748b;width:38%}.notice{background:#fefce8;border-left:3px solid #d4ac0d;margin-top:16px;padding:9px;font-size:8px}</style></head><body>
<header><div class="brand">{{ config('app.name') }}</div><h1>Salinan Data Pribadi</h1><div class="meta">Dibuat {{ $generatedAt->translatedFormat('d F Y, H:i') }} WIB atas permintaan pemilik akun</div></header>
@php($p=$user->penduduk)
<h2>Identitas Kependudukan</h2><table>
<tr><td>Nama lengkap</td><td>{{ $p?->nama ?? $user->name }}</td></tr><tr><td>NIK</td><td>{{ $p?->nik ?? $user->nik ?? '—' }}</td></tr>
<tr><td>Nagari</td><td>{{ $user->nagari?->nama_lengkap ?? $user->nagari?->nama ?? '—' }}</td></tr><tr><td>Tempat, tanggal lahir</td><td>{{ $p?->tempat_lahir ?: '—' }}, {{ $p?->tanggal_lahir?->translatedFormat('d F Y') ?? '—' }}</td></tr>
<tr><td>Jenis kelamin</td><td>{{ $p?->jenis_kelamin?->getLabel() ?? '—' }}</td></tr><tr><td>Agama</td><td>{{ $p?->agama?->nama ?? '—' }}</td></tr>
<tr><td>Pendidikan</td><td>{{ $p?->pendidikan?->nama ?? '—' }}</td></tr><tr><td>Pekerjaan</td><td>{{ $p?->pekerjaan?->nama ?? '—' }}</td></tr><tr><td>Status perkawinan</td><td>{{ $p?->statusPerkawinan?->nama ?? '—' }}</td></tr></table>
<h2>Data Akun</h2><table><tr><td>Email</td><td>{{ $user->email ?? 'Belum diisi' }}</td></tr><tr><td>Nomor HP</td><td>{{ $user->phone ?? 'Belum diisi' }}</td></tr><tr><td>Status akun</td><td>{{ $user->status->value }}</td></tr><tr><td>Akses UMKM</td><td>{{ $user->hasUmkmAccess() ? 'Aktif' : 'Tidak aktif' }}</td></tr><tr><td>Terdaftar</td><td>{{ $user->created_at?->translatedFormat('d F Y, H:i') }}</td></tr></table>
<div class="notice">Dokumen ini memuat data pribadi. Simpan dengan aman dan jangan membagikannya kepada pihak yang tidak berkepentingan.</div></body></html>
